# Generated by Django 4.2.2 on 2023-06-18 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='account_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='nameofuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
