# Generated by Django 4.2.2 on 2023-06-18 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_alter_useraccounts_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='nameofuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
