# Generated by Django 4.2.2 on 2023-06-18 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_alter_useraccounts_nameofuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='nameofuser',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
