# Generated by Django 4.2.2 on 2023-06-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('base_currency', models.CharField(max_length=20)),
                ('registration_date', models.DateTimeField(verbose_name='registration date')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('transaction_date', models.DateTimeField(verbose_name='transaction date')),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoneyOperation.useraccount')),
            ],
        ),
    ]
